name: Update WakaTime stats

on:
  schedule:
    - cron: '40 22 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi graph with new stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_14_days
          SHOW_TIME: true
